version: '3.8'

services:
  postgres:
    image: postgres
    container_name: sitcomdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sitcomdb
    ports:
      - "5432:5432"