spring.application.name=springstudy


spring.datasource.url=jdbc:postgresql://localhost:5432/sitcomdb
spring.datasource.username=postgres
spring.datasource.password=password


spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect